### ISSUE TITLE
K means.

### ISSUE THREAD

**Issue by perogeremmer** [LamaHamadeh/Breast-Cancer#1]
Hello thanks for the code, i wanna ask you somethin. What happened if I decrease K value or Increase it ?

**Comment by LamaHamadeh** [comment]
In case of a k-nearest neighbour method is used, k represents the number of nearest neighbour around a data point. increasing k means simply increasing the neighbouring data around it and decreasing k is the other way around. You should bear in mind two important points here:

1- it is better to choose an odd number of k so you won't get a tie vote 
2- try not to assign a very big value for k so you won't fall into the overfitting problem. 

The typical values for k in most of the problem range between 3 and 9, but there are lots of exceptions of course.

hope this helps!
Lama

**Comment by LamaHamadeh** [comment]
in the case of k-means, k here represents the number of clusters you want to see in your data. Therefore, increasing k means increasing the number of clusters and decreasing k is the other way around. Basically, choosing the number of k in your model is up to you and to the problem itself due to its nature as an unsupervised case, i.e., no labels are known in the data. 

Lama

**Comment by perogeremmer** [comment]
oh its very helpful, thanks lama!
